name: Kotlin CI with Gradle in Docker

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    # Conditional to prevent running this job on push if the push is associated with a pull request
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.event.pull_request == null)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx with docker-container driver
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap

      - name: Build Docker image
        run: docker buildx build --tag graphs-team-11:latest --load .

      - name: Run tests in Docker
        run: docker run --rm graphs-team-11:latest sh -c "xvfb-run -a ./gradlew test --stacktrace"
