name: Lint Code Base

on: [push, pull_request]

jobs:
  bulid:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v6.5.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_KOTLIN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}